<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>
<head>
<meta http-equiv="Content-Type" content="textml; charset=utf-8" />
<?php
	$static = new Common_GetStatic();
	$static->getStaticUrl("easyui");
	$static->getStaticUrl('js','owner_list.js');
?>
<title>智能家园</title>
<script type="text/javascript">
	$(function() { 
		$("#tree").tree({
			url:"<?php $static->getTest('menu.json')?>",
			method:'get',
			lines:true,
			onClick : function(node) {
				if (node.attributes) {
					openTab(node.text, node.attributes.url);
				}
				if (node.text == "编辑评分要素") {
					openPfys();
				}
				else if (node.text == "安全退出") {
					exit();
				}
			}
		});

		function exit() {
			$.messager.confirm('系统提示', '您确定要退出系统吗？', function(r) {
				if (r) {
					window.location.href = '../index.html';
				}
			});
		}

		function openTab(text, url, icon) {
			if ($("#tabs").tabs('exists', text)) {
				$("#tabs").tabs('select', text);
			} else {
				var content = "<iframe frameborder='0' scrolling='auto' style='width:100%;height:100%;' src="
						+ url + "></iframe>";
				$("#tabs").tabs('add', {
					title : text,
					closable : true,
					content : content
				});
			}
		}
	});
</script>
<style>
a{
font-size:14px;
COLOR: #FFF;
}
</style>
</head>

<body class="easyui-layout">
	
	
	<div region="north" style="height:80px; background-image:url(<?php $static->getImg('banner.png'); ?>);background-repeat:no-repeat;" align="center">
    	<div style="margin-left:300px;float:left;padding:0px;">
        	<div style="float:left"><!--用于放logo<img src=""/>--></div><div style="margin-top:20px; float:right"><font color="#fff" size="+3"><b>智能家园</b></font></div>
		</div>
		<div style="margin-top: 55px; margin-right:20px;float:right;padding:0px;">
        <a>欢迎您，<?php echo $jkc ?></a>
		</div>
	</div>
	<div region="west" style="width: 220px;padding: 5px;" title="导航菜单" split="true">
		<ul id="tree" data-options=""></ul>
	</div>
	<div region="center">
		<div class="easyui-tabs" fit="true" border="false" id="tabs">
			<div title="欢迎使用">
				<div style="padding: 10px;">
<pre>
欢迎使用智能家园
</pre>
				</div>
			</div>
		</div>
	</div>
	<div region="south" style="height:30px; background-color:#256cca;" align="center">
		<div style="margin:0px;padding:0px;">
			<table>
                <tr>
                    <td valign="bootom"><font color="white">Copyright 2016 by IcePoint </font></td>
                </tr>
			</table>
		</div>
	</div>	
</body>
</html>
