<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="textml; charset=utf-8" />

<?php
    $static = new Common_GetStatic();
    $static->getStaticUrl("easyui");
    $static->getStaticUrl('js','owner_list.js');
?>
<title>业主列表</title>
</head>
<body>
<table id="dg">
<div id="tb">
<!--<input id="ss"/>-->
<a id="add_btn" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true"/>增加</a>
<a id="edit_btn" class="easyui-linkbutton"  data-options="iconCls:'icon-edit',plain:true">编辑</a>
<a id="rm_btn" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true"/>删除</a>
</div>
</table>

<!--增加-->
<div id="add_dlg">
    <form id="add_fm" method="post" style="margin: 20px;">
        <table>
            <tr>
                <td><label for="name">姓名：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="name" data-options="required:true"
                           missingMessage="请输入姓名" />
                </td>
            </tr>
            <tr>
                <td><label for="name">昵称：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="nickName" data-options="required:true"
                           missingMessage="请输入昵称" />
                </td>
            </tr>
            <tr>
                <td><label for="name">楼号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="dormitoryId" data-options="required:true"
                           missingMessage="请输入楼号" />
                </td>
            </tr>
            <tr>
                <td><label for="name">单元号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="unitId" data-options="required:true"
                           missingMessage="请输入单元号" />
                </td>
            </tr>
            <tr>
                <td><label for="name">房间号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="roomId" data-options="required:true"
                           missingMessage="请输入房间号" />
                </td>
            </tr>

            <tr>
                <td><label for="name">电话号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="phoneNumber" data-options="required:true"
                           missingMessage="请输入电话号" />
                </td>
            </tr>

            <tr>
                <td> <label for="name">请输入IMEI：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="deviceId" data-options="required:true"
                           missingMessage="请输入IMEI" />
                </td>
            </tr>

            <tr>
                <td><label for="name">请输入密码：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="password" name="password" />
                </td>
            </tr>

            <tr>
                <td><label for="name">请重复密码：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="password"  />
                </td>
            </tr>
        </table>
        <div id="dlg-buttons" style="text-align: center;margin-top:20px;">
            <a class="easyui-linkbutton" iconCls="icon-ok" onClick="save(1);">提交</a>
            <a class="easyui-linkbutton" iconCls="icon-cancel" onClick="javascript:$('#add_dlg').dialog('close')">取消</a>
        </div>
    </form>
</div>


<!--编辑-->
<div id="edit_dlg">
    <form id="edit_fm" method="post" style="margin: 20px;">
        <table>
            <input class="easyui-validatebox" type="hidden" name="id" data-options="required:true" />

            <tr>
                <td><label for="name">姓名：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="name" data-options="required:true"
                           missingMessage="请输入姓名" />
                </td>
            </tr>
            <tr>
                <td><label for="name">昵称：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="nickName" data-options="required:true"
                           missingMessage="请输入昵称" />
                </td>
            </tr>
            <tr>
                <td><label for="name">楼号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="dormitoryId" data-options="required:true"
                           missingMessage="请输入楼号" />
                </td>
            </tr>
            <tr>
                <td><label for="name">单元号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="unitId" data-options="required:true"
                           missingMessage="请输入单元号" />
                </td>
            </tr>
            <tr>
                <td><label for="name">房间号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="roomId" data-options="required:true"
                           missingMessage="请输入房间号" />
                </td>
            </tr>

            <tr>
                <td><label for="name">电话号：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="phoneNumber" data-options="required:true"
                           missingMessage="请输入电话号" />
                </td>
            </tr>

            <tr>
                <td> <label for="name">请输入IMEI：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="text" name="deviceId" data-options="required:true"
                           missingMessage="请输入IMEI" />
                </td>
            </tr>

            <tr>
                <td><label for="name">请输入密码：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="password" name="password" />
                </td>
            </tr>

            <tr>
                <td><label for="name">请重复密码：</label></td>
                <td>
                    <input style="width:100px" class="easyui-validatebox" type="password" />
                </td>
            </tr>
        </table>
        <div id="dlg-buttons" style="text-align: center;margin-top:20px;">
            <a class="easyui-linkbutton" iconCls="icon-ok" onClick="save(2);">提交</a>
            <a class="easyui-linkbutton" iconCls="icon-cancel" onClick="javascript:$('#edit_dlg').dialog('close')">取消</a>
        </div>
    </form>
</div>

</body>
</html>
